### PR TITLE
ci: Upload junit results to the pharo5 powered bob-bench.org

### PR DESCRIPTION
**Pull request by zecke**
Upload the junit results created during the test run and add a
badge to the README.md that shows how many tests (, failures
and errors) occurred for the given branch.

### CODE REVIEW

**Comment by zecke** [comment]
Dear Dale,

as a hobby project I have built a pharo5 based service to handle junit files and as first feature generate a badge to show number of tests executed. More things are planned for the future. I would be very happy if you could be an early adopter of it.

**Comment by zecke** [comment]
No upload took place. So please don't merge it yet.

**Comment by zecke** [comment]
Your high number of tests has already reached a column limit in the database backend. At some point I consider exploring Gemstone/S. I promise.

**Comment by dalehenrich** [comment]
Looks interesting. providing test count feedback is nice ... I'll be interested to watch your progress

**Comment by dalehenrich** [comment]
@zecke The badge on the master branch readme shows failures: `1051/2/5`, but the most recent travis builds are green (with the exception of expected failures). When I click on the badge I end up on a page, that claims 266/0/0, so I am curious where the `1051/2/5` badge is coming from and why it does not reflect passing tests ...

**Comment by zecke** [comment]
> On 21 Mar 2017, at 00:53, Dale Henrichs <notifications@github.com> wrote:
> 
> @zecke The badge on the master branch readme shows failures: 1051/2/5, but the most recent travis builds are green (with the exception of expected failures). When I click on the badge I end up on a page, that claims 266/0/0, so I am curious where the 1051/2/5 badge is coming from and why it does not reflect passing tests ...

It is a short coming of how I handle matrix builds. Depending on which build of the matrix finished last it will show different builds.

Travis build 1637.3 had 1053 tests while 1637.4 only 266. I will make the badge always return XYZ.1 in the near future and add API to select a specific sub build.

Thank you for pointing it out!

**Comment by dalehenrich** [comment]
no, thank you!

**Comment by zecke** [comment]
> On 22 Mar 2017, at 18:42, Dale Henrichs <notifications@github.com> wrote:
> 
> no, thank you!


It is picking the results of Build #XYZ._1_ now. I wonder how to present other results of a branch as well. At least the view is now consistent.

holger

**Pull request merged**
